fix: cannot initialize image storage
Image storage directory might contain symlinks.
When using pathlib.iterdir the children are yielded in arbitrary order,
and that might cause a symlink to be processed first, leading to an
error:
  OSError: Cannot call rmtree on a symbolic link

Resolves LP:2048513