revert to use a subclass of threading local to track interface visiting
The current behavior broke rack interfaces processing because of this:

builtins.AttributeError: '_thread._local' object has no attribute 'visiting'